namespace Shipwreck.TypeScriptModels
{
    public enum ExpressionPrecedence
    {
        Unknown = -1,

        Comma = 0,
        Sequence = 0,
        Spread = 1,
        Yield = 2,
        Assignment = 3,
        Conditional = 4,
        LogicalOr = 5,
        LogicalAnd = 6,
        BitwiseOr = 7,
        BitwiseXor = 8,
        BitwiseAnd = 9,
        Equal = 10,
        NotEqual = 10,
        StrictEqual = 10,
        StrictNotEqual = 10,
        LessThan = 11,
        LessThanOrEqual = 11,
        GreaterThan = 11,
        GreaterThanOrEqual = 11,
        In = 11,
        InstanceOf = 11,
        LeftShift = 12,
        RightShift = 12,
        UnsignedRightShift = 12,
        Add = 13,
        Subtract = 13,
        Multiply = 14,
        Divide = 14,
        Modulo = 14,
        Exponent = 15,
        LogicalNot = 16,
        BitwiseNot = 16,
        UnaryPlus = 16,
        UnaryNegation = 16,
        PrefixIncrement = 16,
        PrefixDecrement = 16,
        TypeOf = 16,
        Void = 16,
        Delete = 16,
        PostfixIncrement = 17,
        PostfixDecrement = 17,
        FunctionCall = 18,
        NewWithoutArguments = 18,
        MemberAccess = 19,
        ComputedMemberAccess = 19,
        NewWithArguments = 19,
        Grouping = 20,
    }
}